"""Tenant membership + invitations.

`TenantMember` is the many-to-many between Tenant and User, carrying the role
the user holds in that tenant. `Invite` is a token-link a tenant admin can
share to bring a new user in — the token appears in a URL like
``/dashboard/invites/accept/{token}``.

ID conventions (generated by the route that creates the document; see
``glossa/models/api_key.py`` for the established pattern):

- ``TenantMember.id`` → ``f"mem_{uuid4().hex[:12]}"``
- ``Invite.id`` → ``f"inv_{uuid4().hex[:12]}"``
- ``Invite.token`` → ``secrets.token_urlsafe(32)`` (URL-safe; appears in shared link)
"""

from datetime import datetime
from enum import StrEnum

from pydantic import BaseModel


class TenantRole(StrEnum):
    OWNER = "owner"
    ADMIN = "admin"
    MEMBER = "member"


class TenantMember(BaseModel):
    id: str  # mem_<12 hex>
    tenant_id: str
    user_id: str
    role: TenantRole
    joined_at: datetime


class Invite(BaseModel):
    id: str  # inv_<12 hex>
    tenant_id: str
    token: str  # opaque URL-safe random; matches Invite at /dashboard/invites/accept/{token}
    role: TenantRole
    created_by_user_id: str
    created_at: datetime
    expires_at: datetime
    accepted_at: datetime | None = None
    revoked_at: datetime | None = None


class InviteCreate(BaseModel):
    role: TenantRole = TenantRole.MEMBER
    ttl_hours: int = 168  # 7 days default
