"""Short-lived OAuth auth-code state.

Holds the PKCE ``code_verifier`` and the post-login ``redirect_to`` target
between the redirect to the provider and the callback. The document's ``id``
is the opaque value sent to the provider as the ``state`` query parameter, so
it must be URL-safe and unguessable. Documents are TTL-pruned by Mongo at
``expires_at`` (see ``glossa/db/client.py``); plan on ~10 minute lifetimes.

ID conventions (generated by the route that creates the document; see
``glossa/models/api_key.py`` for the established pattern):

- ``OAuthState.id`` → ``secrets.token_urlsafe(32)`` (no prefix — sent to the OAuth
  provider as the ``state`` query param; some providers limit characters)
"""

from datetime import datetime

from pydantic import BaseModel

from glossa.models.user import OAuthProvider


class OAuthState(BaseModel):
    """Short-lived: ~10 minutes. Holds the PKCE verifier and the post-login redirect target."""

    id: str  # opaque URL-safe random — sent to the provider as the `state` param
    provider: OAuthProvider
    code_verifier: str  # PKCE
    redirect_to: str | None = None  # where to send the user after callback success
    created_at: datetime
    expires_at: datetime
