"""DB-backed cookie sessions for the dashboard.

The session's ``id`` IS the cookie value sent to the browser, so it must be
high-entropy and URL-safe. Sessions are TTL-pruned by Mongo at ``expires_at``
(see ``glossa/db/client.py``).

ID conventions (generated by the route that creates the document; see
``glossa/models/api_key.py`` for the established pattern):

- ``Session.id`` → ``f"ses_{secrets.token_urlsafe(32)}"`` (this IS the cookie value;
  needs to be high-entropy)
"""

from datetime import datetime

from pydantic import BaseModel


class Session(BaseModel):
    id: str  # ses_<urlsafe random — this IS the cookie value>
    user_id: str
    created_at: datetime
    expires_at: datetime
    last_seen_at: datetime
    ip: str | None = None
    user_agent: str | None = None
