"""User + linked OAuth identities.

A `User` is a human dashboard user identified by email. One user may link
multiple external identities (Google, GitHub, ...) — each captured as an
`OAuthAccount` embedded in the user document.

ID conventions (generated by the route that creates the document; see
``glossa/models/api_key.py`` for the established pattern):

- ``User.id`` → ``f"usr_{uuid4().hex[:12]}"``
"""

from datetime import datetime
from enum import StrEnum

from pydantic import BaseModel, Field


class OAuthProvider(StrEnum):
    GOOGLE = "google"
    GITHUB = "github"


class OAuthAccount(BaseModel):
    """One linked external identity on a User."""

    provider: OAuthProvider
    provider_user_id: str  # the provider's stable id (Google sub, GitHub id)
    email: str
    linked_at: datetime


class User(BaseModel):
    id: str  # usr_<12 hex>
    email: str
    name: str
    avatar_url: str | None = None
    oauth_accounts: list[OAuthAccount] = Field(default_factory=list)
    created_at: datetime
    last_login_at: datetime | None = None
